### ISSUE TITLE
Content-Type headers for requests

### ISSUE THREAD

**Issue by pinkgothic** [mjacobus/php-json-api-client#2]
At the moment, headers can only be set globally in the object instantiation, not per-request. This is unfortunately awkward for `Content-Type` headers which make the most sense with the verbs `POST`, `PUT` and `PATCH`, but less with `GET` or `DELETE`. While it's not _required_ per RFC that `Content-Type` be omitted for `GET` and `DELETE` it would be nice if we could make the distinction.

(That said, for `Content-Type` in particular it would help to just be able to supply a `charset` and the class constructing the `Content-Type` header in the background, if you'd rather tackle the specific issue.)

**Comment by mjacobus** [comment]
Hi @pinkgothic. I am happy that someone even tried to use it. Thanks ;-)

Well, it is a json client, so content type should always be json (although it is not explicit  in the code, and it probably should be).

I guess there could be cases where additional headers could be required. Are you consuming any api that does?

I suppose that could be fixed by the introduction of a third param to the request methods. If you like you are welcome to create a PR for that.

**Comment by pinkgothic** [comment]
I see I should've reloaded the page earlier when I added the `charset` comment, wasn't expecting to hear back from you quite so quickly. :)

There are quite a few APIs that bake request parameters into a client secret / signature before they allow the request, which often need to be passed as a header (as a prominent example, AWS does this), so I reckon the general header approach is probably the best option.

I made a pull request here: https://github.com/mjacobus/php-json-api-client/pull/3

This is my first GitHub pull request so please forgive any form errors, I'm happy to learn.

**Comment by pinkgothic** [comment]
Thanks for letting me change this! :)
